/***********************************************************************************************
** Program name: Lab 5
** Author: Jordan Hamilton
** Date: 11/10/2018
** Description: This program displays a menu to the user with options to print a string in
** reverse, to calculate sum of numbers, or to calculate a triangular number. If the user
** selects to print a string in reverse, the user is prompted to enter a string, which is passed
** to the reverseString function to display the string the user enters in reverse. If the user
** selects to sum integers, the user is asked how many integers they would like to sum, then
** is prompted to enter the appropriate number of integers that are then stored in an array in
** a menu object. Menu functions then pass a pointer to the array and an integer representing
** the number of elements in that array to the calcSum function, which returns the total of the
** integers in the array. If the user selects to calculate a triangular number, the user is then
** prompted for a single integer which is passed to the calcTriangularNum function to return
** the triangular number for a triangle with a base with the number of dots the user
** provides. The menu is repeated after any of the above functions complete, or the user may
** quit from the menu.
***********************************************************************************************/

#include "Menu.hpp"
#include "LinkedList.hpp"

void populateMenu(Menu* mainMenu);

/***********************************************************************************************
** Description: This program can be run via the lab6 executable generated by make.
***********************************************************************************************/
int main() {

  int choice;
  Menu *mainMenu = nullptr;
  LinkedList *list = nullptr;

  mainMenu = new Menu("Select from the following options:");
  populateMenu(mainMenu);
  list = new LinkedList;

  do {

    choice = mainMenu->getIntChoiceFromPrompt(1, mainMenu->getMenuChoices(), true);

    switch (choice)  {

      case 1 : list->addHead( mainMenu->getIntChoiceFromPrompt("Enter an integer to add to the beginning of this list", -100000, 100000, false) );
               break;

      case 2 : list->addTail( mainMenu->getIntChoiceFromPrompt("Enter an integer to add the the end of this list", -100000, 100000, false) );
               break;

      case 3 : list->removeHead();
               break;

      case 4 : list->removeTail();
               break;

      case 5 : list->printReversal();
               break;

      default : {}
      
    }

  } while(choice != 6);

  if (list) {
      delete list;
      list = nullptr;
  }

  delete mainMenu;
  mainMenu = nullptr;

  return 0;

}

void populateMenu(Menu* mainMenu) {

  mainMenu->addMenuItem("Add a new node to the head");
  mainMenu->addMenuItem("Add a new node to the tail");
  mainMenu->addMenuItem("Delete a node from the head");
  mainMenu->addMenuItem("Delete a node from the tail");
  mainMenu->addMenuItem("Traverse the list reversely");
  mainMenu->addMenuItem("Exit");

}
